import React, { useState, useRef } from "react";
import { FiUpload, FiX, FiMapPin, FiMail, FiPhone, FiDollarSign, FiStar, FiNavigation, FiLock, FiFileText, FiDownload } from "react-icons/fi";
import axios from "axios";
import { useNavigate } from "react-router-dom";
import jsPDF from "jspdf";

const AddVendorForm = () => {
  const navigate = useNavigate();
  
  const [form, setForm] = useState({
    restaurantName: "",
    description: "",
    locationName: "",
    email: "",
    mobile: "",
    gstNumber: "",
    referralCode: "",
    password: "",
    lat: "",
    lng: "",
    commission: ""
  });

  const [files, setFiles] = useState({
    image: null,
    gstCertificate: null,
    fssaiLicense: null,
    panCard: null,
    aadharCard: null
  });

  const [previews, setPreviews] = useState({
    image: null,
    gstCertificate: null,
    fssaiLicense: null,
    panCard: null,
    aadharCard: null
  });

  const [loading, setLoading] = useState(false);
  const [message, setMessage] = useState("");
  const [showPassword, setShowPassword] = useState(false);

  const fileRefs = {
    image: useRef(null),
    gstCertificate: useRef(null),
    fssaiLicense: useRef(null),
    panCard: useRef(null),
    aadharCard: useRef(null)
  };

  const generateDeclarationPDF = () => {
    const doc = new jsPDF();
    
    // Add green header
    doc.setFillColor(34, 197, 94);
    doc.rect(0, 0, 210, 30, 'F');
    
    // Title
    doc.setFontSize(20);
    doc.setTextColor(255, 255, 255);
    doc.setFont('helvetica', 'bold');
    doc.text('DECLARATION LETTER (PURE VEGETARIAN HOTEL)', 105, 15, { align: 'center' });
    
    // Date section
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    doc.text('Date: ___ / ___ / ______', 20, 45);
    
    // To section
    doc.setFont('helvetica', 'bold');
    doc.text('To', 20, 60);
    doc.setFont('helvetica', 'normal');
    doc.text('Vegiffyy – Pure Vegetarian Food Delivery App', 20, 70);
    doc.text('(Operated by Jainity Eats India Private Limited)', 20, 77);
    
    // Subject
    doc.setFont('helvetica', 'bold');
    doc.text('Subject: Declaration of Pure Vegetarian Restaurant', 20, 92);
    
    // Declaration content
    const declarationText = [
      `I, __________________________, Proprietor / Authorized Signatory of`,
      `Hotel / Restaurant Name: __________________________`,
      `Address: _________________________________________`,
      ``,
      `do hereby solemnly declare and affirm that:`,
      ``,
      `1. Our restaurant / hotel is a 100% Pure Vegetarian establishment.`,
      ``,
      `2. We do not prepare, store, sell, or serve any kind of non-vegetarian food,`,
      `   including egg, meat, fish, or seafood.`,
      ``,
      `3. All ingredients, raw materials, and food preparation processes followed`,
      `   in our premises strictly comply with pure vegetarian standards.`,
      ``,
      `4. We understand that Vegiffyy partners exclusively with vegetarian vendors,`,
      `   and any violation of this declaration may lead to immediate delisting`,
      `   or termination from the platform.`,
      ``,
      `5. We confirm that the information provided above is true and correct to`,
      `   the best of our knowledge and belief.`,
      ``,
      `This declaration is provided for the purpose of onboarding and continued`,
      `association with Vegiffyy.`,
      ``,
      `Vendor Name: __________________________`,
      `Authorized Person Name: __________________________`,
      `Designation: __________________________`,
      `Mobile Number: __________________________`,
      `Signature: __________________________`
    ];

    let yPosition = 110;
    declarationText.forEach(line => {
      if (yPosition > 270) {
        doc.addPage();
        yPosition = 20;
      }
      doc.setFontSize(10);
      doc.text(line, 20, yPosition);
      yPosition += 6;
    });

    // Add footer
    doc.setFontSize(8);
    doc.setTextColor(100, 100, 100);
    doc.text('Generated by Vegiffyy - India\'s Trusted Pure Vegetarian Food Platform', 105, 285, { align: 'center' });

    // Save the PDF
    doc.save('Vegiffyy-Declaration-Form.pdf');
  };

  const generateVendorAgreementPDF = () => {
    const doc = new jsPDF();
    
    // Add green header
    doc.setFillColor(34, 197, 94);
    doc.rect(0, 0, 210, 30, 'F');
    
    // Title
    doc.setFontSize(18);
    doc.setTextColor(255, 255, 255);
    doc.setFont('helvetica', 'bold');
    doc.text('VENDOR AGREEMENT', 105, 15, { align: 'center' });
    
    // Date
    doc.setFontSize(10);
    doc.setTextColor(255, 255, 255);
    doc.text('Date: ___ / ___ / _________', 20, 25);
    
    // Reset text color for content
    doc.setTextColor(0, 0, 0);
    
    // Agreement content
    const agreementContent = [
      "This Vendor Agreement (\"Agreement\") is made and entered into on ___ / ___ / _________",
      "",
      "BETWEEN",
      "",
      "Jainity Eats India Private Limited,",
      "A company incorporated under the Companies Act, 2013,",
      "Having its registered office at:",
      "781, Sadar Bazaar, Bolarum, Secunderabad, Telangana – 500010",
      "(Hereinafter referred to as \"Company\", which expression shall include its successors and assigns)",
      "",
      "AND",
      "",
      "Vendor Name: ______________________________",
      "Business Address: ____________________________",
      "Type of Business: Pure Vegetarian Hotel / Restaurant / Sweet Shop / Juice Center",
      "(Hereinafter referred to as \"Vendor\")",
      "",
      "The Company and Vendor are hereinafter individually referred to as a \"Party\" and collectively as the \"Parties\".",
      "---",
      "1. PURPOSE OF AGREEMENT",
      "The Vendor agrees to list and sell 100% Pure Vegetarian food products through the Company's",
      "mobile application \"Vegiffyy\", owned and operated by Jainity Eats India Private Limited.",
      "---",
      "2. VENDOR DECLARATION",
      "The Vendor hereby declares and confirms that:",
      "- The establishment serves only Pure Vegetarian food.",
      "- No non-vegetarian food, eggs, or related products are prepared or sold.",
      "- The Vendor shall maintain hygiene, food safety, and quality standards as per applicable laws.",
      "---",
      "3. COMMISSION & PAYMENT",
      `The Vendor agrees to pay the Company a commission of ${form.commission || "_____"} % on each`,
      "successful order processed through the Vegiffyy platform.",
      "Payments shall be settled as per the Company's payout cycle, after deducting applicable",
      "taxes, charges, and commissions.",
      "---",
      "4. ORDER FULFILLMENT",
      "The Vendor shall prepare and deliver orders within the time committed on the Vegiffyy app.",
      "The Vendor is responsible for food quality, portion size, and proper packaging.",
      "Any complaints regarding food quality will be the Vendor's responsibility.",
      "---",
      "5. DELIVERY",
      "Delivery may be managed by the Company or Vendor, based on mutual understanding.",
      "The Company may offer free delivery on orders above ₹199, subject to Company policies.",
      "---",
      "6. BRANDING & INTELLECTUAL PROPERTY",
      "The Vendor allows the Company to display the Vendor's name, menu, logo, and images on the",
      "Vegiffyy platform for marketing purposes.",
      "This Agreement does not transfer ownership of any intellectual property to either Party.",
      "---",
      "7. TERM & TERMINATION",
      "This Agreement shall be valid from the date mentioned above and remain in force until terminated.",
      "Either Party may terminate this Agreement by giving 15 days' written notice.",
      "Immediate termination may occur in case of breach, misrepresentation, or violation of",
      "vegetarian commitment.",
      "---",
      "8. COMPLIANCE WITH LAWS",
      "The Vendor shall comply with:",
      "- FSSAI regulations",
      "- GST and local municipal rules",
      "- All applicable food and safety laws",
      "---",
      "9. CONFIDENTIALITY",
      "Both Parties agree to keep all business, financial, and customer-related information confidential.",
      "---",
      "10. GOVERNING LAW & JURISDICTION",
      "This Agreement shall be governed by and construed in accordance with the laws of India.",
      "Courts of Telangana shall have exclusive jurisdiction.",
      "---",
      "11. ENTIRE AGREEMENT",
      "This Agreement constitutes the entire understanding between the Parties and supersedes all",
      "prior discussions or agreements.",
      "---",
      "IN WITNESS WHEREOF, the Parties have hereunto set their hands on the date first written above.",
      "---",
      "For Jainity Eats India Private Limited",
      "",
      "Authorized Signatory: ________________________",
      "Name: ________________________",
      "Designation: ________________________",
      "Signature: ________________________",
      "Date: ________________________",
      "",
      "---",
      "For Vendor",
      "",
      "Vendor Name: ________________________",
      "Authorized Signatory: ________________________",
      "Signature: ________________________",
      "Date: ________________________"
    ];

    let yPosition = 40;
    doc.setFontSize(9);
    
    agreementContent.forEach(line => {
      if (yPosition > 280) {
        doc.addPage();
        yPosition = 20;
      }
      
      if (line.startsWith("---")) {
        // Draw a line for section separators
        doc.line(20, yPosition, 190, yPosition);
        yPosition += 8;
      } else if (line.includes("AGREEMENT") || line.match(/^\d+\./)) {
        // Section headers
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(10);
        doc.text(line, 20, yPosition);
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(9);
        yPosition += 6;
      } else {
        doc.text(line, 20, yPosition);
        yPosition += 5;
      }
    });

    // Add footer
    doc.setFontSize(8);
    doc.setTextColor(100, 100, 100);
    doc.text('Generated by Vegiffyy - India\'s Trusted Pure Vegetarian Food Platform', 105, 285, { align: 'center' });

    // Save the PDF
    doc.save('Vegiffyy-Vendor-Agreement.pdf');
  };

  const handleChange = (e) => {
    setForm(prev => ({ ...prev, [e.target.name]: e.target.value }));
  };

  const handleFileChange = (fileType, file) => {
    if (!file) return;

    setFiles(prev => ({ ...prev, [fileType]: file }));
    
    if (file.type.startsWith('image/')) {
      const reader = new FileReader();
      reader.onload = () => {
        setPreviews(prev => ({ ...prev, [fileType]: reader.result }));
      };
      reader.readAsDataURL(file);
    } else {
      setPreviews(prev => ({ ...prev, [fileType]: 'pdf' }));
    }
  };

  const removeFile = (fileType) => {
    setFiles(prev => ({ ...prev, [fileType]: null }));
    setPreviews(prev => ({ ...prev, [fileType]: null }));
  };

  const getCurrentLocation = () => {
    if (!navigator.geolocation) {
      setMessage("Geolocation not supported");
      return;
    }

    navigator.geolocation.getCurrentPosition(
      (position) => {
        const { latitude, longitude } = position.coords;
        setForm(prev => ({
          ...prev,
          lat: latitude.toFixed(6),
          lng: longitude.toFixed(6)
        }));
        setMessage("Location fetched successfully");
      },
      (error) => {
        setMessage("Failed to get location");
      }
    );
  };

  const validateForm = () => {
    if (!form.restaurantName) return "Restaurant name is required";
    if (!form.locationName) return "Location name is required";
    if (!form.email) return "Email is required";
    if (!form.mobile) return "Mobile is required";
    if (!form.password) return "Password is required";
    if (form.password.length < 6) return "Password must be at least 6 characters";
    if (!form.commission) return "Commission percentage is required";
    if (isNaN(form.commission) || parseFloat(form.commission) < 0 || parseFloat(form.commission) > 50) return "Commission must be a valid percentage between 0 and 50";
    if (!form.lat || !form.lng) return "Location coordinates are required";
    if (!files.image) return "Restaurant image is required";
    if (!files.fssaiLicense) return "FSSAI license is required";
    if (!files.panCard) return "PAN card is required";
    if (!files.aadharCard) return "Aadhar card is required";
    return null;
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    
    const error = validateForm();
    if (error) {
      setMessage(error);
      return;
    }

    setLoading(true);
    setMessage("");

    try {
      const formData = new FormData();
      
      // Add form fields
      Object.keys(form).forEach(key => {
        if (form[key]) formData.append(key, form[key]);
      });

      // Add files
      Object.keys(files).forEach(key => {
        if (files[key]) formData.append(key, files[key]);
      });

      const res = await axios.post("http://31.97.206.144:5051/api/restaurant", formData);
      
      if (res.data.success) {
        setMessage("Restaurant created successfully!");
        setTimeout(() => navigate("/"), 2000);
      } else {
        setMessage(res.data.message || "Creation failed");
      }
    } catch (err) {
      setMessage(err.response?.data?.message || "Server error");
    } finally {
      setLoading(false);
    }
  };

  const FileUpload = ({ title, fileType, required = false, accept = "image/*,.pdf" }) => (
    <div className="border-2 border-green-200 rounded-xl p-4 bg-green-50 hover:bg-green-100 transition-all duration-300">
      <label className="block font-bold text-green-800 mb-2">
        {title} {required && <span className="text-red-500">*</span>}
      </label>
      
      <div className="flex items-center gap-4">
        {previews[fileType] ? (
          <div className="relative">
            {previews[fileType] === 'pdf' ? (
              <div className="w-20 h-20 bg-red-100 rounded-xl border-2 border-red-300 flex items-center justify-center shadow-lg">
                <FiFileText className="text-red-600 text-2xl" />
              </div>
            ) : (
              <img src={previews[fileType]} alt="Preview" className="w-20 h-20 rounded-xl border-2 border-green-300 object-cover shadow-lg" />
            )}
            <button
              type="button"
              onClick={() => removeFile(fileType)}
              className="absolute -top-2 -right-2 bg-red-500 text-white rounded-full p-1 hover:bg-red-600 transition-colors shadow-lg"
            >
              <FiX size={12} />
            </button>
          </div>
        ) : (
          <div className="w-20 h-20 border-2 border-dashed border-green-300 rounded-xl flex items-center justify-center text-green-400 bg-white">
            <FiUpload className="text-2xl" />
          </div>
        )}
        
        <div>
          <input
            type="file"
            ref={fileRefs[fileType]}
            className="hidden"
            accept={accept}
            onChange={(e) => handleFileChange(fileType, e.target.files[0])}
          />
          <button
            type="button"
            onClick={() => fileRefs[fileType].current?.click()}
            className="bg-gradient-to-r from-green-600 to-green-800 text-white px-6 py-3 rounded-xl hover:from-green-700 hover:to-green-900 transition-all duration-300 shadow-lg hover:shadow-xl transform hover:scale-105 font-bold flex items-center gap-2"
          >
            <FiUpload />
            Choose File
          </button>
          {files[fileType] && (
            <p className="text-sm text-green-700 font-medium mt-2">{files[fileType].name}</p>
          )}
        </div>
      </div>
    </div>
  );

  return (
    <div className="min-h-screen bg-gradient-to-br from-green-50 to-white py-8 px-4">
      <div className="max-w-4xl mx-auto bg-white rounded-2xl shadow-2xl border-2 border-green-200 overflow-hidden">
        {/* Header */}
        <div className="bg-gradient-to-r from-green-600 to-green-800 text-white p-8">
          <div className="flex items-center justify-between">
            <div>
              <h1 className="text-3xl font-black mb-2">Add New Restaurant</h1>
              <p className="text-green-100 font-medium">Join India's Trusted Pure Vegetarian Food Platform</p>
            </div>
            <div className="w-16 h-16 bg-white bg-opacity-20 rounded-2xl flex items-center justify-center text-2xl">
              🏪
            </div>
          </div>
        </div>

        <form onSubmit={handleSubmit} className="p-8 space-y-8">
          {/* Restaurant Image */}
          <FileUpload title="🍽️ Restaurant Image" fileType="image" required accept="image/*" />

          {/* Basic Details */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div className="space-y-2">
              <label className="block font-bold text-green-800 mb-2">🏷️ Restaurant Name *</label>
              <input
                type="text"
                name="restaurantName"
                value={form.restaurantName}
                onChange={handleChange}
                className="w-full border-2 border-green-200 rounded-xl px-4 py-3 focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-green-500 transition-all duration-300"
                placeholder="Enter restaurant name"
              />
            </div>

            <div className="space-y-2">
              <label className="block font-bold text-green-800 mb-2">📍 Location Name *</label>
              <input
                type="text"
                name="locationName"
                value={form.locationName}
                onChange={handleChange}
                className="w-full border-2 border-green-200 rounded-xl px-4 py-3 focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-green-500 transition-all duration-300"
                placeholder="Enter location name"
              />
            </div>

            <div className="space-y-2">
              <label className="block font-bold text-green-800 mb-2">📧 Email *</label>
              <input
                type="email"
                name="email"
                value={form.email}
                onChange={handleChange}
                className="w-full border-2 border-green-200 rounded-xl px-4 py-3 focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-green-500 transition-all duration-300"
                placeholder="Enter email"
              />
            </div>

            <div className="space-y-2">
              <label className="block font-bold text-green-800 mb-2">📱 Mobile *</label>
              <input
                type="tel"
                name="mobile"
                value={form.mobile}
                onChange={handleChange}
                className="w-full border-2 border-green-200 rounded-xl px-4 py-3 focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-green-500 transition-all duration-300"
                placeholder="Enter mobile number"
              />
            </div>

            <div className="space-y-2">
              <label className="block font-bold text-green-800 mb-2">🔐 Password *</label>
              <div className="relative">
                <input
                  type={showPassword ? "text" : "password"}
                  name="password"
                  value={form.password}
                  onChange={handleChange}
                  className="w-full border-2 border-green-200 rounded-xl px-4 py-3 focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-green-500 transition-all duration-300 pr-20"
                  placeholder="Enter password"
                />
                <button
                  type="button"
                  onClick={() => setShowPassword(!showPassword)}
                  className="absolute right-3 top-3 text-green-600 font-medium hover:text-green-800 transition-colors"
                >
                  {showPassword ? "🙈 Hide" : "👁️ Show"}
                </button>
              </div>
            </div>

            <div className="space-y-2">
              <label className="block font-bold text-green-800 mb-2">
                💰 Commission % *
              </label>
              <div className="relative">
                <input
                  type="number"
                  name="commission"
                  value={form.commission}
                  onChange={handleChange}
                  className="w-full border-2 border-green-200 rounded-xl px-4 py-3 focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-green-500 transition-all duration-300 pr-16"
                  placeholder="Enter commission percentage"
                  min="0"
                  max="50"
                  step="0.1"
                  required
                />
                <div className="absolute right-3 top-3 text-green-600 font-bold">
                  %
                </div>
              </div>
              <p className="text-sm text-green-600 mt-1">
                Commission percentage applied on each order
              </p>
            </div>

            <div className="space-y-2">
              <label className="block font-bold text-green-800 mb-2">📊 GST Number</label>
              <input
                type="text"
                name="gstNumber"
                value={form.gstNumber}
                onChange={handleChange}
                className="w-full border-2 border-green-200 rounded-xl px-4 py-3 focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-green-500 transition-all duration-300"
                placeholder="Enter GST number"
              />
            </div>
          </div>

          {/* Documents */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <FileUpload title="📄 GST Certificate" fileType="gstCertificate" />
            <FileUpload title="🥘 FSSAI License *" fileType="fssaiLicense" required />
            <FileUpload title="💳 PAN Card *" fileType="panCard" required />
            <FileUpload title="🆔 Aadhar Card *" fileType="aadharCard" required />
          </div>

          {/* Location */}
          <div className="border-2 border-green-200 rounded-2xl p-6 bg-green-50 hover:bg-green-100 transition-all duration-300">
            <div className="flex flex-col md:flex-row justify-between items-start md:items-center mb-6 gap-4">
              <div>
                <h3 className="font-bold text-green-800 text-xl mb-2">📍 Location Coordinates *</h3>
                <p className="text-green-700">Get your current location automatically</p>
              </div>
              <button
                type="button"
                onClick={getCurrentLocation}
                className="bg-gradient-to-r from-green-500 to-green-700 text-white px-6 py-3 rounded-xl hover:from-green-600 hover:to-green-800 transition-all duration-300 shadow-lg hover:shadow-xl transform hover:scale-105 font-bold flex items-center gap-2 whitespace-nowrap"
              >
                <FiNavigation />
                Get Current Location
              </button>
            </div>
            
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div className="space-y-2">
                <label className="block font-bold text-green-800 mb-2">🌐 Latitude</label>
                <input
                  type="number"
                  step="any"
                  name="lat"
                  value={form.lat}
                  onChange={handleChange}
                  className="w-full border-2 border-green-200 rounded-xl px-4 py-3 focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-green-500 transition-all duration-300"
                  placeholder="Enter latitude"
                />
              </div>
              
              <div className="space-y-2">
                <label className="block font-bold text-green-800 mb-2">🌐 Longitude</label>
                <input
                  type="number"
                  step="any"
                  name="lng"
                  value={form.lng}
                  onChange={handleChange}
                  className="w-full border-2 border-green-200 rounded-xl px-4 py-3 focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-green-500 transition-all duration-300"
                  placeholder="Enter longitude"
                />
              </div>
            </div>
          </div>

          {/* Description */}
          <div className="space-y-2">
            <label className="block font-bold text-green-800 mb-2">📝 Description</label>
            <textarea
              name="description"
              rows="4"
              value={form.description}
              onChange={handleChange}
              className="w-full border-2 border-green-200 rounded-xl px-4 py-3 focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-green-500 transition-all duration-300"
              placeholder="Tell us about your restaurant..."
            />
          </div>

          {/* Referral Code */}
          <div className="space-y-2">
            <label className="block font-bold text-green-800 mb-2">👥 Referral Code (Optional)</label>
            <input
              type="text"
              name="referralCode"
              value={form.referralCode}
              onChange={handleChange}
              className="w-full border-2 border-green-200 rounded-xl px-4 py-3 focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-green-500 transition-all duration-300"
              placeholder="Enter referral code"
            />
          </div>

          {/* Document Download Buttons */}
          <div className="border-2 border-blue-200 rounded-2xl p-6 bg-blue-50">
            <h3 className="font-bold text-blue-800 text-xl mb-4">📄 Download Required Documents</h3>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <button
                type="button"
                onClick={generateDeclarationPDF}
                className="bg-gradient-to-r from-blue-500 to-blue-700 text-white px-6 py-4 rounded-xl hover:from-blue-600 hover:to-blue-800 transition-all duration-300 shadow-lg hover:shadow-xl transform hover:scale-105 font-bold flex items-center justify-center gap-3"
              >
                <FiDownload className="text-xl" />
                Download Declaration Form
              </button>
              
              <button
                type="button"
                onClick={generateVendorAgreementPDF}
                className="bg-gradient-to-r from-purple-500 to-purple-700 text-white px-6 py-4 rounded-xl hover:from-purple-600 hover:to-purple-800 transition-all duration-300 shadow-lg hover:shadow-xl transform hover:scale-105 font-bold flex items-center justify-center gap-3"
              >
                <FiFileText className="text-xl" />
                Download Vendor Agreement
              </button>
            </div>
            <p className="text-blue-700 text-sm mt-3 text-center">
              Please download, print, sign, and upload these documents after filling
            </p>
          </div>

          {/* Submit Buttons */}
          <div className="flex flex-col md:flex-row gap-4 pt-6 border-t-2 border-green-200">
            <button
              type="submit"
              disabled={loading}
              className="bg-gradient-to-r from-green-600 to-green-800 text-white px-8 py-4 rounded-xl hover:from-green-700 hover:to-green-900 disabled:opacity-50 transition-all duration-300 shadow-2xl hover:shadow-3xl transform hover:scale-105 font-bold text-lg flex items-center justify-center gap-3 flex-1"
            >
              {loading ? (
                <>
                  <div className="w-5 h-5 border-2 border-white border-t-transparent rounded-full animate-spin"></div>
                  Creating Restaurant...
                </>
              ) : (
                <>
                  🏪 Create Restaurant
                </>
              )}
            </button>
            
            <button
              type="button"
              onClick={() => navigate("/vendorlist")}
              className="border-2 border-red-500 text-red-500 hover:bg-red-500 hover:text-white px-8 py-4 rounded-xl transition-all duration-300 shadow-lg hover:shadow-xl transform hover:scale-105 font-bold text-lg flex items-center justify-center gap-3 flex-1"
            >
              ❌ Cancel
            </button>
          </div>

          {message && (
            <div className={`p-4 rounded-xl border-2 font-bold text-center ${
              message.includes("successfully") 
                ? "bg-green-100 text-green-800 border-green-300" 
                : "bg-red-100 text-red-800 border-red-300"
            }`}>
              {message}
            </div>
          )}
        </form>
      </div>
    </div>
  );
};

export default AddVendorForm;